### ISSUE TITLE
試験日程について

### ISSUE THREAD

**Issue by knorth55** [k-okada/2015-soft3#270]
試験日程は私は13日だと把握しているのですが、13日で間違っていないでしょうか？
それとも6日のまま変更はされていないのでしょうか？
情報が錯綜していて確認をさせてください。よろしくお願いします。

**Comment by k-okada** [comment]
13日に行います

--
◉ Kei Okada

2016/01/03 22:03、Shingo Kitagawa <notifications@github.com> のメッセージ:

**Comment by knorth55** [comment]
返答ありがとうございます。
