### ISSUE TITLE
20151209の課題について

### ISSUE THREAD

**Issue by pazeshun** [k-okada/2015-soft3#286]
20151209のディレクトリはいつごろ追加されるのでしょうか。
なるべく早く追加していただけるとありがたいです。
それとも、僕達が自分で追加するべきなのでしょうか。
その場合、travisによる試験は大丈夫なのでしょうか。

**Comment by k-okada** [comment]
https://github.com/k-okada/2015-soft3/pull/287
ついかしました．もう提出している人はそのままでOKです．

## 

◉ Kei Okada

2016-01-09 11:19 GMT+09:00 pazeshun notifications@github.com:

**Comment by pazeshun** [comment]
ありがとうございます
