### ISSUE TITLE
20151014の練習問題1-3について

### ISSUE THREAD

**Issue by knorth55** [k-okada/2015-soft3#73]
与えられたrenshu-1.lの中に
```
(assert (eq (X #'list 1 nil) '(1)) "mondai 3")
```
とあるのですが、CommonLispだとeq関数はメモリー番地まで同じものでないといけないと調べたら書いてありました。これはequal関数に変更してもいいでしょうか？
```
(assert (equal (X #'list 1 nil) '(1)) "mondai 3")
```

**Comment by k-okada** [comment]
たしかに、そうですね。https://github.com/k-okada/2015-soft3/commit/e031945ac6a402490b1a78e4743744a86bb6db51
で修正しておきました

**Comment by knorth55** [comment]
ありがとうございます。
