### ISSUE TITLE
20151014の課題について

### ISSUE THREAD

**Issue by szxnkl** [k-okada/2015-soft3#89]
enshu_20151014というパッケージ名になっていますが、travis上ではbeginner_tutorialsという名前のパッケージでチェックを行おうとしているのでエラーが出ます。

**Comment by k-okada** [comment]
https://github.com/k-okada/2015-soft3/pull/86
これは，直さないとダメですね．

**Comment by k-okada** [comment]
https://github.com/k-okada/2015-soft3/commit/dce15882b62499189656981f6ea2e4ce40bdcec6
で直しました．パッケージ名非依存になったはずです．

**Comment by szxnkl** [comment]
対応ありがとうございます。
